### ISSUE TITLE
LyX 编译为 PDF 需开启 -shell-escape 选项

### ISSUE THREAD

**Issue by e71828** [pvcStillInGradSchool/miniWiki#6]
## 【错误概述】Describe the Bug
无法编译到pdf
## 【复现步骤】To Reproduce
主选项卡---> Document--->view other formats ---> PDF(xetex)
## 【期望效果】Expected Behaviour
pdf veiw

## 【软件版本】Software Versions
- OS: [e.g. windows10.14]
- Texlive: 2019

## 【其他信息】Additional Context
**enclosure**
[README.log](https://github.com/pvcStillInGradSchool/miniWiki/files/4889312/README.log)

**Comment by muzimuzhi** [comment]
```
! Package minted Error: You must invoke LaTeX with the -shell-escape flag.
```

**Comment by e71828** [comment]
这个warning 我没搞懂啊

**Comment by muzimuzhi** [comment]
文件调用了 `minted` 宏包，该宏包要求使用 `-shell-escape` 选项。去修改编辑器的配置，增加相应选项。如果不知道如何修改配置，请提供正在使用的编辑器名字和版本信息。

**Comment by e71828** [comment]
```
LyX Version 2.3.5-1
(Tuesday, June 2, 2020
```

**Comment by pvc1989** [comment]
> 这个warning 我没搞懂啊

原因 @muzimuzhi 已经解释了。
解决方法：LyX 顶栏的【文档】→【首选项】→【输出格式】→【允许运行外部程序】打钩

**Comment by e71828** [comment]
ok
