### ISSUE TITLE
转成网页后，对应子标题 #Ninja 的目录项跳转失败

### ISSUE THREAD

**Issue by muzimuzhi** [pvcStillInGradSchool/miniWiki#9]
## 【错误概述】Describe the Bug

 - [programming/make/README.md](https://github.com/pvcStillInGradSchool/miniWiki/blob/master/programming/make/README.md) 中，目录部分有内部链接 `[Ninja](#Ninja)`，正文有标题 `#Ninja`。
 - github 在预览 markdown 时，点击目录能成功跳转到正文对应位置
 - 对应的网页 https://pvcstillingradschool.github.io/miniWiki/programming/make 中，目录部分为 `<a href="#Ninja">Ninja</a>`，正文为 `<h1 id="ninja">Ninja</h1>`。正文里生成的是小写的 `ninja`，导致点击目录跳转失败。

## 【复现步骤】To Reproduce
1. 访问 https://pvcstillingradschool.github.io/miniWiki/programming/make/
1. 点击目录部分的 `Ninja`，跳转失败

## 可能的修复方案

文件 [programming/make/README.md](https://github.com/pvcStillInGradSchool/miniWiki/blob/master/programming/make/README.md) 里已经有多处手动添加的超链接目标，再加一个肯定能解决问题。

也可以考虑自动生成 markdown/html 的目录。了解为什么转出来的 html id attribute 名总是小写的，应该也挺有意思。

**Comment by muzimuzhi** [comment]
补充信息：
 - 侧边栏的目录，跳转正常
 - 根据 HTML: The Markup Language, [sec. 3.4 _Case insensitivity in tag names and attribute names_](https://w3c.github.io/html-reference/documents.html#case-insensitivity)，attribute name 在 html 规范里大小写不敏感，在 xml 规范里大小写敏感。

**Comment by pvc1989** [comment]
> ## 【错误概述】Describe the Bug
> * [programming/make/README.md](https://github.com/pvcStillInGradSchool/miniWiki/blob/master/programming/make/README.md) 中，目录部分有内部链接 `[Ninja](#Ninja)`，正文有标题 `#Ninja`。
> * github 在预览 markdown 时，点击目录能成功跳转到正文对应位置
> * 对应的网页 https://pvcstillingradschool.github.io/miniWiki/programming/make 中，目录部分为 `<a href="#Ninja">Ninja</a>`，正文为 `<h1 id="ninja">Ninja</h1>`。正文里生成的是小写的 `ninja`，导致点击目录跳转失败。
> 
> ## 【复现步骤】To Reproduce
> 1. 访问 https://pvcstillingradschool.github.io/miniWiki/programming/make/
> 2. 点击目录部分的 `Ninja`，跳转失败
> 
> ## 可能的修复方案
> 文件 [programming/make/README.md](https://github.com/pvcStillInGradSchool/miniWiki/blob/master/programming/make/README.md) 里已经有多处手动添加的超链接目标，再加一个肯定能解决问题。
> 
> 也可以考虑自动生成 markdown/html 的目录。了解为什么转出来的 html id attribute 名总是小写的，应该也挺有意思。

CMake 也有同样的问题。
